### PR TITLE
Fixes #7 ImportError flask.ext.cache -> flask_cache

### LINKED ISSUE #7: ImportError: No module named ext.cache
[root@localhost trunk]# gdash 
Traceback (most recent call last):
  File "/usr/bin/gdash", line 9, in <module>
    load_entry_point('gdash==0.4', 'console_scripts', 'gdash')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/gdash/app.py", line 12, in <module>
    from flask.ext.cache import Cache
ImportError: No module named ext.cache

### PR DESCRIPTION
**Pull request by pirate**

### CODE REVIEW

**Comment by aravindavk** [comment]
Thanks for the PR, Any change required to https://github.com/aravindavk/gdash/blob/master/setup.py file?

**Comment by pirate** [comment]
No, but it's still broken due to this:

```python3
  File "/usr/local/lib/python2.7/dist-packages/flask_cache/jinja2ext.py", line 33, in <module>
    from flask.ext.cache import make_template_fragment_key
ImportError: No module named ext.cache
```
The same patch just needs to be applied to `/usr/local/lib/python2.7/dist-packages/flask_cache/jinja2ext.py` the problem is that package got deprecated and is no longer accepting PRs as far as I can tell. Manually editing the file locally is a pain, but it works for now, maybe we can just add a message to the readme with instructions.

**Comment by aravindavk** [comment]
Ack. I will look into this error next week. I am planning to use Cherrypy instead of Flask for two reasons, 1) It has inbuilt production grade http server 2) Native support for cache.

**Side note**: As part of a Elixir Phoenix contest(https://phoenixphrenzy.com/) I started a Gluster dashboard project. It is not yet ready for production.

Repo is here: https://github.com/aravindavk/gluster-dashboard
Blog about that project: https://aravindavk.in/blog/elixir-phoenix-liveview-gluster-dashboard/

**Comment by pirate** [comment]
Cool, no rush as I'm not actually using this dashboard any longer, but figured it might be an easy fix.  No worries if you want to archive/deprecated this repo instead.

**Comment by aravindavk** [comment]
Closing this issue. gdash is rewritten using Cherrypy Python and ReactJS.

**Pull request closed without merging**
