### PR TITLE
Auto format codebase to py36+

### PR DESCRIPTION
**Pull request by gaby**
The main purpose of this PR is to auto-format the python codebase using: black, isort, and pyupgrade. Using pyupgrade we are able to auto-upgrade the codebase to be py36+, and deprecating support for EOL python versions.

Signed-off-by: Juan Calderon <jgcalderonperez@protonmail.com>

### CODE REVIEW

**Comment by gaby** [comment]
After formatting and several fixes this is the report by Pylint:

```
ubuntu@ubuntu:~/Desktop/git/fix/gdash$ pylint *.py */*.py
************* Module setup
setup.py:1:0: C0114: Missing module docstring (missing-module-docstring)
setup.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
setup.py:5:4: C0415: Import outside toplevel (gdash.version.VERSION) (import-outside-toplevel)
************* Module gdash.__main__
gdash/__main__.py:8:0: E0401: Unable to import 'cherrypy' (import-error)
gdash/__main__.py:9:0: E0401: Unable to import 'glustercli.cli' (import-error)
gdash/__main__.py:33:0: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:47:0: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:54:0: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:61:0: C0115: Missing class docstring (missing-class-docstring)
gdash/__main__.py:63:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:77:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:90:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:97:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:109:0: C0115: Missing class docstring (missing-class-docstring)
gdash/__main__.py:113:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:119:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:123:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:123:22: W0613: Unused argument 'volume_id' (unused-argument)
gdash/__main__.py:127:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:131:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:135:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:139:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:143:4: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:147:0: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:180:0: C0116: Missing function or method docstring (missing-function-docstring)
gdash/__main__.py:181:4: W0603: Using the global statement (global-statement)

------------------------------------------------------------------
Your code has been rated at 7.19/10
```

**Review by aravindavk — APPROVED** [review]

**Comment by aravindavk** [comment]
Thanks for the PR.

**Comment by gaby** [comment]
@aravindavk Any plans to publish a new release to Pypi? 😁

**Comment by gaby** [comment]
> > @aravindavk Any plans to publish a new release to Pypi? grin
> 
> Today I tried to upgrade the React dependencies. But failing while running `npm audit fix`. Let me try to fix that by tomorrow, else we can release without updating the UI dependencies.

Locally I was only able to run the UI with Node 14. Using 16/17/18 would cause the build to fail.

**Pull request merged**
